version: "3.8"
services:
  tower:
    image: cosmtrek/air
    working_dir: /app
    command: server
    container_name: runic
    ports:
      - '<no value>:<no value>'
    volumes:
      - ./:/app
    # depends_on:
    #   - db
    #   - redis
    #   - nats
