// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, runicClient } from '.';

export interface ParserTitleRequest {
  title: string;
  type: string;
}

export const ParserTitle = async (params: ParserTitleRequest) => {
  const response = await runicClient.get(`/parser/title?title=${params.title}&type=${params.type}`);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as Response;
};

export interface ParserParseRequest {
  title: string;
  type: string;
}

export const ParserParse = async (params: ParserParseRequest) => {
  const response = await runicClient.get(`/parser/parse?title=${params.title}&type=${params.type}`);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as Response;
};
