version: "2.0"
name: runic
repo: github.com/dashotv/runic
package: app
output: internal/app
plugins:
    models: true
    routes: true
    workers: true
    cache: true
    events: true
    clients: true
definitions:
    models: .golem/models
    routes: .golem/routes
    events: .golem/events
    workers: .golem/workers
    queues: .golem/queues
    clients: .golem/clients
