name: sources
path: /sources
rest: true
routes:
  - name: read
    path: /:id/read
    method: GET
    params:
      - name: id
        type: string
  - name: search
    path: /:id/search
    method: GET
    params:
      - name: id
        type: string
      - name: q
        type: string
        query: true
      - name: t
        type: string
        query: true
