FROM node:latest

ARG GITHUB_TOKEN
ENV GITHUB_TOKEN $GITHUB_TOKEN

WORKDIR /usr/src/app

RUN echo //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN > ./.npmrc
RUN echo @dashotv:registry=https://npm.pkg.github.com/ >> ./.npmrc
COPY package.json package-lock.json ./
RUN npm install --include=dev

COPY . .
